// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fsvVCJNXhN88gnWPeurk82
// Component: Yqol-rCxsy
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import HeaderNav from "../../HeaderNav" // plasmic-import: yzN9e7yMUD/component
import Footer from "../../Footer" // plasmic-import: BxuEl8DsYN/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_vtapi_co.module.css" // plasmic-import: fsvVCJNXhN88gnWPeurk82/projectcss
import * as sty from "./PlasmicWhatsAnApi.module.css" // plasmic-import: Yqol-rCxsy/css
import ApiFastfoodsvgIcon from "./icons/PlasmicIcon__ApiFastfoodsvg" // plasmic-import: -hAnRVCEc/icon

export const PlasmicWhatsAnApi__VariantProps = new Array()

export const PlasmicWhatsAnApi__ArgProps = new Array()

function PlasmicWhatsAnApi__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeaderNav
            data-plasmic-name={"headerNav"}
            data-plasmic-override={overrides.headerNav}
            className={classNames("__wab_instance", sty.headerNav)}
          />

          <div className={classNames(defaultcss.all, sty.box__rnx3J)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__js9Ov
              )}
            >
              {"What's an API?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__aKsk9
              )}
            >
              {"The term API stands for:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__gZzS8
              )}
            >
              {"Application Programming Interface"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qDsqH
              )}
            >
              {"What does that mean in plain english?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qaIkn
              )}
            >
              {
                "It's a way for programmers or systems to automate communication between software that is designed to be modular, extendable or integrated into other systems. \n"
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__rIs05
              )}
            >
              {"APIs are the glue that connect modern software and networks."}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___0Jaeo
              )}
            >
              {
                "One of the best real-world examples of an API that most people have interacted with is the menu and speaker found at any drive-through or fast food restaurant."
              }
            </div>

            <ApiFastfoodsvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(defaultcss.all, sty.svg)}
              role={"img"}
            />

            <div className={classNames(defaultcss.all, sty.box__u4F4)}>
              <div className={classNames(defaultcss.all, sty.box__lOzVx)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___7Z5Bs
                  )}
                >
                  {"It provides several pieces of what define an API:"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__wpHkY)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nCrHk
                  )}
                >
                  {"It has information about what options are available"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__rZoVh
                  )}
                >
                  {
                    "It allows you to make requests and receive predictable responses"
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__yfYyz
                  )}
                >
                  {"It reduces transactional friction"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__s9Vlx
                  )}
                >
                  {"It integrates with an existing system or infrastructure."}
                </div>
              </div>
            </div>
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__rTiy
            )}
          >
            {
              "Whether you are building software from scratch or extending an existing platform, you're going to have to deal with APIs at some point. Our years of experience allow us to to consider not only the issues directly impacting software, but concerns that will arise in the future that will make or break the ability to communicate with external systems."
            }
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___8DbFj
            )}
          >
            {"Do you need help with an API?"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__mrXE
            )}
          >
            {
              "We can help fix things, we love to build new ideas, and we most enjoy helping organizations to achieve competency so they can take the baton and continue success even in our absence. "
            }
          </div>

          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link
            )}
            component={Link}
            href={"/contact"}
            platform={"gatsby"}
          >
            {"Contact us today to get started."}
          </p.PlasmicLink>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "headerNav", "svg", "link", "footer"],
  headerNav: ["headerNav"],
  svg: ["svg"],
  link: ["link"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWhatsAnApi__ArgProps,
      internalVariantPropNames: PlasmicWhatsAnApi__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicWhatsAnApi__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicWhatsAnApi"
  } else {
    func.displayName = `PlasmicWhatsAnApi.${nodeName}`
  }
  return func
}

export const PlasmicWhatsAnApi = Object.assign(
  // Top-level PlasmicWhatsAnApi renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    svg: makeNodeComponent("svg"),
    link: makeNodeComponent("link"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicWhatsAnApi
    internalVariantProps: PlasmicWhatsAnApi__VariantProps,
    internalArgProps: PlasmicWhatsAnApi__ArgProps,
  }
)

export default PlasmicWhatsAnApi
/* prettier-ignore-end */
