// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fsvVCJNXhN88gnWPeurk82
// Component: Yqol-rCxsy
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import HeaderNav from "../../HeaderNav" // plasmic-import: yzN9e7yMUD/component
import Footer from "../../Footer" // plasmic-import: BxuEl8DsYN/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_vtapi_co.module.css" // plasmic-import: fsvVCJNXhN88gnWPeurk82/projectcss
import * as sty from "./PlasmicWhatIsAnApi.module.css" // plasmic-import: Yqol-rCxsy/css
import ApiFastfoodsvgIcon from "./icons/PlasmicIcon__ApiFastfoodsvg" // plasmic-import: -hAnRVCEc/icon

export const PlasmicWhatIsAnApi__VariantProps = new Array()

export const PlasmicWhatIsAnApi__ArgProps = new Array()

function PlasmicWhatIsAnApi__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeaderNav
            data-plasmic-name={"headerNav"}
            data-plasmic-override={overrides.headerNav}
            className={classNames("__wab_instance", sty.headerNav)}
          />

          <div className={classNames(defaultcss.all, sty.box__rnx3J)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__js9Ov
              )}
            >
              {"What is an API?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__aKsk9
              )}
            >
              {"The term API stands for:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__gZzS8
              )}
            >
              {"Application Programming Interface"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qDsqH
              )}
            >
              {"What does that mean in plain english?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qaIkn
              )}
            >
              {
                "It's a way for developers to automate systems and software designed to be modular, extendable or integrated into other systems. \n"
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wcCAy
              )}
            >
              {"Ok uh... what's an API again?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__rIs05
              )}
            >
              {"APIs are the glue that connect modern software and networks."}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___0Jaeo
              )}
            >
              {"At its core, an API is simply:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qFbkx
              )}
            >
              {"An Interface"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__iaTW
              )}
            >
              {
                "One of the best real-world examples of an API that most people have interacted with is the menu and speaker found at any drive-through or fast food restaurant."
              }
            </div>

            <ApiFastfoodsvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(defaultcss.all, sty.svg)}
              role={"img"}
            />

            <div className={classNames(defaultcss.all, sty.box__u4F4)}>
              <div className={classNames(defaultcss.all, sty.box__lOzVx)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___7Z5Bs
                  )}
                >
                  {"What Does an API do?"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__wpHkY)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nCrHk
                  )}
                >
                  {
                    "It provides information about what options are available and the status of the system"
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__rZoVh
                  )}
                >
                  {
                    "It allows you to make requests and receive predictable responses"
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__yfYyz
                  )}
                >
                  {"It reduces transactional friction"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__s9Vlx
                  )}
                >
                  {"It integrates with an existing system or infrastructure."}
                </div>
              </div>
            </div>
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__rTiy
            )}
          >
            {
              "Whether you are building software from scratch or extending an existing platform, you're going to have to deal with APIs at some point. Our  experience building new systems and integrating with services can help anticipate problems and improve outcomes."
            }
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___4Diln
            )}
          >
            {
              "There are several kinds of things that are all correctly defined as APIs:"
            }
          </div>

          <div className={classNames(defaultcss.all, sty.box__oj4RL)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__nAd6Z
              )}
            >
              {"1. Software:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___54RT
              )}
            >
              {
                "A library, module or other piece of code published and maintained by a specific organization. It can be included into existing software projects or packages to allow developers to integrate functionality."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___3Mz8P
              )}
            >
              {"Examples:"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__vstYq)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__uxzTc)}
              >
                <p.PlasmicLink
                  className={classNames(defaultcss.all, sty.link__o9Omp)}
                  component={Link}
                  href={
                    "https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html"
                  }
                  platform={"gatsby"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__yy9U)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__es8LF
                      )}
                    >
                      {"AWS SDK"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___5DWuz
                      )}
                    >
                      {"Example"}
                    </div>
                  </p.Stack>
                </p.PlasmicLink>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__ctr0F)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__pBZe
                  )}
                >
                  {"Google Maps"}
                </div>

                <p.PlasmicLink
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__jXhtJ
                  )}
                  component={Link}
                  href={
                    "https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html"
                  }
                  platform={"gatsby"}
                >
                  {"Example"}
                </p.PlasmicLink>
              </p.Stack>
            </p.Stack>
          </div>

          <div className={classNames(defaultcss.all, sty.box__c842Q)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__oSTqX
              )}
            >
              {"2. Service:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__nRpeE
              )}
            >
              {
                "A URL and corresponding servers that execute behavior on behalf of the user. Developers can write code that causes the API to perform an action and report on the outcome. Every API described as a Service is powered by at least one, but sometimes many Applications."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__kw0X8
              )}
            >
              {"Examples:"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__bvNtE)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__vAf5B)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__fm6Ew
                  )}
                >
                  {"Stripe"}
                </div>

                <p.PlasmicLink
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__peXa
                  )}
                  component={Link}
                  href={"https://stripe.com/docs/api"}
                  platform={"gatsby"}
                >
                  {"Example"}
                </p.PlasmicLink>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__mGrXg)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___2TIbL
                  )}
                >
                  {"Twilio"}
                </div>

                <p.PlasmicLink
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__ppvGu
                  )}
                  component={Link}
                  href={"https://www.twilio.com/docs/sms"}
                  platform={"gatsby"}
                >
                  {"Example"}
                </p.PlasmicLink>
              </p.Stack>
            </p.Stack>
          </div>

          <div className={classNames(defaultcss.all, sty.box__zshJ6)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__ooPLo
              )}
            >
              {"3. Application:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xLVp
              )}
            >
              {
                "A collection of code that runs on a server and responds to requests from other systems. Similar to Service above, but this definition specifically refers to either a dedicated interface to data or functionality or an additional interface separate from the main frontend or backend.  Applications are the building blocks that power Services."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___25Pz
              )}
            >
              {"Examples:"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__sZoiu)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box___4Rtfb)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__g8Cjw
                  )}
                >
                  {"Wordpress API"}
                </div>

                <p.PlasmicLink
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__mdwcq
                  )}
                  component={Link}
                  href={"https://developer.wordpress.org/rest-api/"}
                  platform={"gatsby"}
                >
                  {"Example"}
                </p.PlasmicLink>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__sWmaF)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___8Pew
                  )}
                >
                  {"Hapi"}
                </div>

                <p.PlasmicLink
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__cKt6E
                  )}
                  component={Link}
                  href={"https://hapi.dev/tutorials/?lang=en_US#-overview"}
                  platform={"gatsby"}
                >
                  {"Example"}
                </p.PlasmicLink>
              </p.Stack>
            </p.Stack>
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___8DbFj
            )}
          >
            {"Do you know what \nkind of API you \nneed help with?"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__iv7Qz
            )}
          >
            {"We can help figuring out that too!"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__mrXE
            )}
          >
            {
              "Whether you're designing something new or adding on to an existing system, our expertise and experience can help ensure your API solutions are effective and successful."
            }
          </div>

          <p.PlasmicLink
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link__edrGr
            )}
            component={Link}
            href={"/contact"}
            platform={"gatsby"}
          >
            {"Contact us today to get started."}
          </p.PlasmicLink>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "headerNav", "svg", "footer"],
  headerNav: ["headerNav"],
  svg: ["svg"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWhatIsAnApi__ArgProps,
      internalVariantPropNames: PlasmicWhatIsAnApi__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicWhatIsAnApi__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicWhatIsAnApi"
  } else {
    func.displayName = `PlasmicWhatIsAnApi.${nodeName}`
  }
  return func
}

export const PlasmicWhatIsAnApi = Object.assign(
  // Top-level PlasmicWhatIsAnApi renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicWhatIsAnApi
    internalVariantProps: PlasmicWhatIsAnApi__VariantProps,
    internalArgProps: PlasmicWhatIsAnApi__ArgProps,
  }
)

export default PlasmicWhatIsAnApi
/* prettier-ignore-end */
