// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fsvVCJNXhN88gnWPeurk82
// Component: ZfeuDm0ZNOg
import * as React from "react"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_vtapi_co.module.css" // plasmic-import: fsvVCJNXhN88gnWPeurk82/projectcss
import * as sty from "./PlasmicServiceList.module.css" // plasmic-import: ZfeuDm0ZNOg/css
import TopCapsvgIcon from "./icons/PlasmicIcon__TopCapsvg" // plasmic-import: 0WV9Nxs3k/icon
import DividersvgIcon from "./icons/PlasmicIcon__Dividersvg" // plasmic-import: b6SG-iotH/icon

export const PlasmicServiceList__VariantProps = new Array()

export const PlasmicServiceList__ArgProps = new Array()

function PlasmicServiceList__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__wRi2A
        )}
      >
        {"Services:"}
      </div>

      <TopCapsvgIcon
        className={classNames(defaultcss.all, sty.svg__ddTpV)}
        role={"img"}
      />

      <div className={classNames(defaultcss.all, sty.box__qSsck)}>
        <div className={classNames(defaultcss.all, sty.box__vuq9Y)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__osAl1
            )}
          >
            {"Research and Discovery"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__zz8G9
            )}
          >
            {
              "Figuring out how to solve business problems using technology requires understanding of both the challenge as well as the solution applied. By combining years of experience using off the shelf tools, CMS systems and completely bespoke platforms we can help organizations achieve their goals whether it’s rapid prototyping or a sustainable and extendable system to power their business."
            }
          </div>
        </div>
      </div>

      <DividersvgIcon
        className={classNames(defaultcss.all, sty.svg__gh85P)}
        role={"img"}
      />

      <div className={classNames(defaultcss.all, sty.box___3EoYd)}>
        <div className={classNames(defaultcss.all, sty.box__v3OGf)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__ecCxF
            )}
          >
            {"Project Roadmapping"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__z5OJt
            )}
          >
            {
              "Determining project scope and navigating the order of things to build on a software project can be challenging at best. By setting your project up with a solid procedural foundation you can be nimble and adapt to feedback and QA instead of accumulating unfocused work like a ball of mud. Ruthless prioritization and focused attention on the essentials ensure the M in your MVP is taken seriously."
            }
          </div>
        </div>
      </div>

      <DividersvgIcon
        className={classNames(defaultcss.all, sty.svg__bLJcG)}
        role={"img"}
      />

      <div className={classNames(defaultcss.all, sty.box___8SiN)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__mHaMn
          )}
        >
          {"Application Development"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__jHe2X
          )}
        >
          {
            "Developing custom applications takes more than writing code. It’s a combination of knowing when to use off the shelf tools and when to make something uniquely tailored to your challenges. By leveraging existing open source technologies we can help companies find and implement sustainable technology solutions."
          }
        </div>
      </div>

      <DividersvgIcon
        className={classNames(defaultcss.all, sty.svg__tvsH6)}
        role={"img"}
      />

      <div className={classNames(defaultcss.all, sty.box__re8Vm)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__y5Rof
          )}
        >
          {"Linux Systems Adminstration"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__hfhU
          )}
        >
          {
            "Whether it’s for running systems on cloud providers, or getting local development environments set up to coordinate between disparate teams, experience with the command line is key to developing and maintaining infrastructure. Our expertise with setup and administration of systems means we can help get existing software running on new machines or take advantage of low cost and battle tested software methodologies that won’t tie you to a single cloud provider."
          }
        </div>
      </div>

      <DividersvgIcon
        className={classNames(defaultcss.all, sty.svg__oQhhz)}
        role={"img"}
      />

      <div className={classNames(defaultcss.all, sty.box__khoaX)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__pMn1X
          )}
        >
          {"Creative Services"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__cqNIr
          )}
        >
          {
            "It’s one thing to make a functional system, but it helps when things look nice too. We’re not afraid to roll up our sleeves and mess with font weights, color pallets and even identity branding. Creativity has never been something we’ve shied away from and it’s part of our special sauce. For more insight into the creative mastermind check out www.robotdrawsyou.com to learn what happens when vector artwork and pen plotters collide."
          }
        </div>
      </div>
    </div>
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServiceList__ArgProps,
      internalVariantPropNames: PlasmicServiceList__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicServiceList__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicServiceList"
  } else {
    func.displayName = `PlasmicServiceList.${nodeName}`
  }
  return func
}

export const PlasmicServiceList = Object.assign(
  // Top-level PlasmicServiceList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicServiceList
    internalVariantProps: PlasmicServiceList__VariantProps,
    internalArgProps: PlasmicServiceList__ArgProps,
  }
)

export default PlasmicServiceList
/* prettier-ignore-end */
