// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fsvVCJNXhN88gnWPeurk82
// Component: jFPPIhVElfu
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_vtapi_co.module.css" // plasmic-import: fsvVCJNXhN88gnWPeurk82/projectcss
import * as sty from "./PlasmicProfileWithDetails.module.css" // plasmic-import: jFPPIhVElfu/css
import DividersvgIcon from "./icons/PlasmicIcon__Dividersvg" // plasmic-import: b6SG-iotH/icon
import matAtVtccGKh8Vu5OS from "./images/matAtVtcc.jpeg" // plasmic-import: gKH8Vu5oS/picture

export const PlasmicProfileWithDetails__VariantProps = new Array()

export const PlasmicProfileWithDetails__ArgProps = new Array()

function PlasmicProfileWithDetails__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__vYxTe)}>
        <div className={classNames(defaultcss.all, sty.box__udN6S)}>
          <div className={classNames(defaultcss.all, sty.box___0Sud2)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___6O0F
              )}
            >
              {"Who: "}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__vLgqW
              )}
            >
              {"Mat Gilbert"}
            </div>
          </div>

          <DividersvgIcon
            className={classNames(defaultcss.all, sty.svg__aq2W)}
            role={"img"}
          />

          <div className={classNames(defaultcss.all, sty.box__r3I63)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__dsEFs
              )}
            >
              {"What:"}
            </div>

            <div className={classNames(defaultcss.all, sty.box__za4Vc)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__mu4H
                )}
              >
                {"vtapi.co "}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__kPj9S
                )}
              >
                {"aka Vermont API, LLC"}
              </div>
            </div>
          </div>

          <DividersvgIcon
            className={classNames(defaultcss.all, sty.svg__mhjjf)}
            role={"img"}
          />

          <div className={classNames(defaultcss.all, sty.box__vaZhH)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___7Uewz
              )}
            >
              {"When:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__fmTbz
              )}
            >
              {"Since 2019"}
            </div>
          </div>

          <div className={classNames(defaultcss.all, sty.box__eKxqa)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wzE4
              )}
            >
              {"Where:"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__daA1
              )}
            >
              {"Vermont, the greater Burlington area."}
            </div>
          </div>

          <DividersvgIcon
            className={classNames(defaultcss.all, sty.svg__tkQv0)}
            role={"img"}
          />

          <div className={classNames(defaultcss.all, sty.box__bGio)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__t4Ihu
              )}
            >
              {"Why ? "}
            </div>
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__vHnwy
            )}
          >
            {
              "To improve understanding of web technologies and help organizations improve efficiency."
            }
          </div>

          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link
            )}
            component={Link}
            href={"/values"}
            platform={"gatsby"}
          >
            {"Learn more about our Values"}
          </p.PlasmicLink>
        </div>

        <div className={classNames(defaultcss.all, sty.box___6BFx)}>
          <img
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(defaultcss.img, sty.img)}
            role={"img"}
            src={matAtVtccGKh8Vu5OS}
          />
        </div>
      </div>
    </div>
  )
}

const PlasmicDescendants = {
  root: ["root", "link", "img"],
  link: ["link"],
  img: ["img"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProfileWithDetails__ArgProps,
      internalVariantPropNames: PlasmicProfileWithDetails__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicProfileWithDetails__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicProfileWithDetails"
  } else {
    func.displayName = `PlasmicProfileWithDetails.${nodeName}`
  }
  return func
}

export const PlasmicProfileWithDetails = Object.assign(
  // Top-level PlasmicProfileWithDetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicProfileWithDetails
    internalVariantProps: PlasmicProfileWithDetails__VariantProps,
    internalArgProps: PlasmicProfileWithDetails__ArgProps,
  }
)

export default PlasmicProfileWithDetails
/* prettier-ignore-end */
