// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fsvVCJNXhN88gnWPeurk82
// Component: UmzKSsgGvq
import * as React from "react"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import HeaderNav from "../../HeaderNav" // plasmic-import: yzN9e7yMUD/component
import ProfileWithDetails from "../../ProfileWithDetails" // plasmic-import: jFPPIhVElfu/component
import Footer from "../../Footer" // plasmic-import: BxuEl8DsYN/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_vtapi_co.module.css" // plasmic-import: fsvVCJNXhN88gnWPeurk82/projectcss
import * as sty from "./PlasmicAbout.module.css" // plasmic-import: UmzKSsgGvq/css

export const PlasmicAbout__VariantProps = new Array()

export const PlasmicAbout__ArgProps = new Array()

function PlasmicAbout__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeaderNav
            data-plasmic-name={"headerNav"}
            data-plasmic-override={overrides.headerNav}
            className={classNames("__wab_instance", sty.headerNav)}
          />

          <ProfileWithDetails
            data-plasmic-name={"profileWithDetails"}
            data-plasmic-override={overrides.profileWithDetails}
            className={classNames("__wab_instance", sty.profileWithDetails)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "headerNav", "profileWithDetails", "footer"],
  headerNav: ["headerNav"],
  profileWithDetails: ["profileWithDetails"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAbout__ArgProps,
      internalVariantPropNames: PlasmicAbout__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout"
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`
  }
  return func
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    profileWithDetails: makeNodeComponent("profileWithDetails"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps,
  }
)

export default PlasmicAbout
/* prettier-ignore-end */
