// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fsvVCJNXhN88gnWPeurk82
// Component: MvXdLCc8OV
import * as React from "react"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import HeaderNav from "../../HeaderNav" // plasmic-import: yzN9e7yMUD/component
import ServiceList from "../../ServiceList" // plasmic-import: ZfeuDm0ZNOg/component
import Footer from "../../Footer" // plasmic-import: BxuEl8DsYN/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_vtapi_co.module.css" // plasmic-import: fsvVCJNXhN88gnWPeurk82/projectcss
import * as sty from "./PlasmicServices.module.css" // plasmic-import: MvXdLCc8OV/css

export const PlasmicServices__VariantProps = new Array()

export const PlasmicServices__ArgProps = new Array()

function PlasmicServices__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeaderNav
            data-plasmic-name={"headerNav"}
            data-plasmic-override={overrides.headerNav}
            className={classNames("__wab_instance", sty.headerNav)}
          />

          <div
            data-plasmic-name={"box"}
            data-plasmic-override={overrides.box}
            className={classNames(defaultcss.all, sty.box)}
          >
            <ServiceList
              data-plasmic-name={"serviceList"}
              data-plasmic-override={overrides.serviceList}
              className={classNames("__wab_instance", sty.serviceList)}
            />
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "headerNav", "box", "serviceList", "footer"],
  headerNav: ["headerNav"],
  box: ["box", "serviceList"],
  serviceList: ["serviceList"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServices__ArgProps,
      internalVariantPropNames: PlasmicServices__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicServices"
  } else {
    func.displayName = `PlasmicServices.${nodeName}`
  }
  return func
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    box: makeNodeComponent("box"),
    serviceList: makeNodeComponent("serviceList"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,
  }
)

export default PlasmicServices
/* prettier-ignore-end */
